INSERT INTO products (sku, name, price, description, tags, image_url) VALUES 
('PVN214', 'Trứng tôm EBIKO 500g (hộp)', 240000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN213', 'Há cảo gà 25 viên (bịch)', 70000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN212', 'Xíu mại 25 viên (bịch)', 70000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN211', 'Há cảo củ dền 25 viên (bịch)', 70000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN210', 'Há cảo thạch lam 25 viên (bịch)', 70000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN209', 'Xúc xích tiệt trùng RED CP (thùng)', 360000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN208', 'Phô mai lát EMBORG 1.033kg (bịch)', 230000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('PVN207', 'Bột ớt Nongwoo Mịn 1kg (bịch)', 125000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN206', 'Phô mai viên TA 500g (vỉ)', 45000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('PVN205', 'Viên thả lẩu trứng cá Phú Mark 450g (gói)', 50000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('PVN204', 'Gân bò Y (kg)', 125000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN203', 'Kim chi túi 5kg', 60000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('PVN202', 'Xốt ướp bò Bulgogi CJ 10Kg (can)', 620000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN201', 'Bánh gạo truyền thống Green đỏ 500g (gói)', 30000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('ccx', 'Chả cá xoắn Naruto Maki 160g (cây)', 45000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('skrose', 'Xốt Rose O!Sajang 500g (gói)', 80000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN200', 'Chả mực xoắn Chojo 454g (gói)', 45000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN199', 'Đùi gà chiên giòn CP 1.6kg (bịch)', 180000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gà rán/Gà chiên']::TEXT[], NULL),
('sk3', 'Tương ớt Hàn Quốc - Loại 3 (gói)', 50000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN197', 'Lạp xưởng nướng đá UTZ 600g (gói)', 85000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN196', 'Lườn cá hồi 12kg (thùng)', 95000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN195', 'Xúc xích phô mai PM 500g (gói)', 45000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá', 'Phô mai']::TEXT[], NULL),
('PVN194', 'Chân gà rút xương Thành Đạt NET9 (bịch)', 100000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('PVN193', 'Bao tử cá basa (kg)', 75000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN192', 'Bào ngư N6 (bịch)', 165000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN190', 'Râu bạch tuộc (bịch)', 60000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN189', 'Sandwich cá EB 500g (gói)', 85000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN188', 'Túi tiền trứng cá EB 150g (gói)', 75000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('PVN187', 'Bánh gạo bắp phô mai Green Foods 500g (gói)', 55000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Bánh gạo/Tokbokki', 'Phô mai']::TEXT[], NULL),
('PVN186', 'Bánh gạo cầu vồng Green Foods 500g (gói)', 35000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('PVN185', 'Bột gia vị phô mai O!Sajang 100g', 25000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Gia vị & Xốt', 'Phô mai']::TEXT[], NULL),
('PVN184', 'Mì không gói gia vị CHINNO [14 gói] 1.050Kg (túi)', 100000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN183', 'Gói gia vị mì Koreno Jumbo vị bò cay 1Kg', 60000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN182', 'Xốt Mayonnaise KEWPIE 3Kg', 200000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN181', 'Gói gia vị mì Koreno Jumbo vị kim chi 1Kg', 80000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN180', 'Rong biển vụn KWOOK 1kg (gói)', 380000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('PVN179', 'Gia vị lẩu kim chi 1KG (bịch)', 100000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN178', 'Bánh gạo Green Foods Xanh 1Kg (gói)', 60000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('gh', 'Gừng hồng SHOGA ZUKE 1.5Kg (bịch)', 135000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('xmr', 'Xốt mè rang KEWPIE 1L (chai)', 180000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN177', 'Nước tương JIN SINGSONG 13L (can)', 500000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN176', 'BỘT CHIÊN GÀ HMF 1Kg (bịch)', 75000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('gcrb3', 'Gà cuộn rong biển CP 300g (gói)', 50000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Rong biển']::TEXT[], NULL),
('PVN174', 'Rong biển nấu canh K-WOOK 200g (gói)', 110000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('PVN173', 'Tôm hùm viên EB 500g (gói)', 90000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('ccv2.5', 'Củ cải vàng 2.5kg (hộp)', 120000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN171', 'Bánh gạo thỏi xiên Green xanh 500g (gói)', 35000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('PVN170', 'Cá viên Tân Khánh 500g (gói)', 25000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('PVN169', 'Chả giò rế 400g (gói)', 45000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Xúc xích & Chả cá', 'Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('bbks', 'Bánh bao kim sa LC (gói)', 30000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL);