INSERT INTO products (sku, name, price, description, tags, image_url) VALUES 
('gc', 'Gà cuộn rong biển CP 1kg (gói)', 150000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Rong biển']::TEXT[], NULL),
('rbcj', 'Rong biển Natureat CJ 100 lá (gói)', 275000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('km', 'Tokbokki Khoai Môn GF 500g (gói)', 55000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('kl', 'Tokbokki Khoai Lang GF 500g (gói)', 55000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('PVN165', 'Thịt cuộn Kimbap HAM SAJO (1Kg)', 165000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('mandu2', 'Bánh Mandu Bibigo CJ nhân thịt 1.505Kg (bịch)', 160000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('sk2', 'Tương ớt Hàn Quốc - Loại 2 (gói)', 50000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('skden', 'Tương đen O!Sajang 500g (gói)', 50000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN161', 'Xốt gà chiên Chungwoo vị ngọt 10kg (can)', 650000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gia vị & Xốt', 'Gà rán/Gà chiên']::TEXT[], NULL),
('udon', 'Mì Udon Bongojang 200g (thùng)', 780000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN160', 'Mì KORENO JUMBO (gói)', 8000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN159', 'Bột ớt HaeChamMat Cánh To (kg)', 125000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN158', 'Gia vị nấu ăn ngon 2L (chai)', 110000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('bom', 'Bột ớt HaeChamMat Mịn (kg)', 125000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN156', 'Rong biển cuộn cơm 50 lá (gói)', 125000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('xgn', 'Xốt gà CHUNGWOO vị chua ngọt 2.1kg (chai)', 160000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN154', 'Tương trộn ăn liền CJ hộp 500g', 60000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN153', 'Rượu nấu ăn Mirin 1.8L (chai)', 275000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN152', 'Bột gà rán BEKSUL CJ 5kg (bịch)', 450000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gia vị & Xốt', 'Gà rán/Gà chiên']::TEXT[], NULL),
('nondo', 'Trứng gà non đỏ (kg)', 95000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('sake', 'Rượu nấu ăn SAKE 20L (thùng)', 0, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('ntn', 'Nước tương Nhật KIKKOMAN 18L (thùng)', 0, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('krn', 'Mì Koreno Jumbo bò cay (Thùng)', 500000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN150', 'Mực viên LC 500g (gói)', 45000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN149', 'Hạt nêm vị bò cay 1kg (bịch)', 95000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('mandu1', 'Bánh Mandu Bibigo CJ nhân thịt bắp 1.505Kg (bịch)', 160000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN147', 'Rong biển Mi-Yeok 50g (gói)', 40000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('bc', 'Bò cuộn (vỉ 500g)', 105000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN145', 'Rong biển vụn 500G (gói)', 190000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('PVN143', 'Lạp Xưởng Nướng Đá Đài Loan', 85000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('Cj14', 'Tương ớt Gochujang CJ 14kg (thùng)', 800000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN141', 'Tương chấm thịt nướng CJ 450g', 75000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN140', 'Bò lát (kg)', 120000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN139', 'Ốc nhồi Tân Khánh 500g (gói)', 35000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Khác']::TEXT[], NULL),
('PVN138', 'Dầu mè Singsong 1.8L (chai)', 290000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN137', 'Chả cốm Hà Nội 500g (gói)', 35000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN135', 'Kimbap chiên 700g (hộp)', 65000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('Klk', 'Khoai lang kén 250g (gói)', 20000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('Td', 'Tương đậu CJ thùng 14kg (thùng)', 700000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN134', 'Bột ớt Nongwoo To 1kg (bịch)', 125000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('Mv', 'Mực vòng Nugget 1kg (bịch)', 95000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN132', 'Phô mai que An Khang (vỉ)', 45000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('tccj', 'Thanh cua Chojo 500g (gói)', 50000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('chd', 'Cua Viên Huỳnh Đế 454 (bịch)', 50000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('Cj1kg', 'Tương ớt Gochujang 1kg (hộp)', 140000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('ccv', 'Củ cải vàng 2.7kg (hộp)', 150000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN127', 'Bột phô mai HQ 1kg (bịch)', 130000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Gia vị & Xốt', 'Phô mai']::TEXT[], NULL),
('Xxdr', 'Xúc xích DORY 500g (bịch)', 55000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN125', 'Khoai tây lốc xoáy (gói 10 cây)', 70000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('PVN124', 'Bánh bạch tuộc 1.2kg (gói)', 140000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL);