INSERT INTO products (sku, name, price, description, tags, image_url) VALUES 
('PVN272', 'Mì Udon Deuchi 50 gói (thùng)', 800000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN271', 'Xốt Teriyaki dạng túi (2Kg)', 130000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN270', 'Mandu Mini 990g (bịch)', 130000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN269', 'Giấm táo Ottogi 20L', 500000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('cvkm', 'Bánh Quả Cầu Vàng 300g (hộp)', 45000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('PVN267', 'Cá viên xốt Mayonnaise Anny 500g (vỉ)', 40000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Gia vị & Xốt', 'Viên thả lẩu']::TEXT[], NULL),
('PVN262', 'Khoai tây lốc xoáy 5 cây (bịch)', 40000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('PVN261', 'Bột ớt Albit Cánh to 1kg (bịch)', 115000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN260', 'Bánh gạo phô mai Greenfood 500g (gói)', 60000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Bánh gạo/Tokbokki', 'Phô mai']::TEXT[], NULL),
('PVN259', 'Bánh gạo sợi DOORE 1kg (bịch)', 70000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('PVN258', 'Miến khoai mỡ tròn 250g (bịch)', 30000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Mì Hàn Quốc']::TEXT[], NULL),
('PVN257', 'Viên thả lẩu Chojo Vàng 454g (gói)', 50000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('PVN256', 'Xúc xích hồ lô Bevin 500g (gói)', 45000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN255', 'Đậu hủ phô mai ĐP 450g (bịch)', 50000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('PVN253', 'Bánh bao xanh dài LC 12 cái (bịch)', 25000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN252', 'Gà KARAAGE CP 1Kg (bịch)', 120000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gà rán/Gà chiên']::TEXT[], NULL),
('PVN251', 'Phô mai Mozzarella bào Ngọc Hải 500g (túi)', 85000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('PVN249', 'Bột ớt Albit Mịn 1kg (bịch)', 115000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN248', 'Đường nâu SEOUL 1Kg (bịch)', 60000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN247', 'Khoai tây Hungritos 10mm (bịch)', 60000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('pmk2', 'Phô mai khối Golden 2Kg (khối)', 270000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('PVN245', 'Mì CHINNOO không gia vị - Thùng 168 gói (thùng)', 1050000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN244', 'Há cảo thịt 25 viên (bịch)', 70000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN243', 'Cánh gà rán CP 1.3Kg (bịch)', 150000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gà rán/Gà chiên']::TEXT[], NULL),
('PVN242', 'Nem chua rán 5S (hộp)', 50000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('PVN241', 'Bánh sữa tươi Dr.GION 500g (hộp)', 50000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN240', 'Chả con tôm 500g (bịch)', 40000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN239', 'Miến khoai Arirang 1Kg', 70000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Mì Hàn Quốc']::TEXT[], NULL),
('PVN238', 'Rong biển vụn NONGWOO 1kg (gói)', 450000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('PVN237', 'Sốt gà chiên vị phô mai O''Food 2.5Kg (túi)', 250000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Gia vị & Xốt', 'Phô mai', 'Gà rán/Gà chiên']::TEXT[], NULL),
('PVN236', 'Cánh gà rán CP 1.5Kg (bịch)', 150000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gà rán/Gà chiên']::TEXT[], NULL),
('PVN235', 'Xốt Teriyaki OTTOGI 2.25Kg (can)', 165000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN234', 'Xốt gà rán OTTOGI vị cay 2,4Kg (can)', 160000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gia vị & Xốt', 'Gà rán/Gà chiên']::TEXT[], NULL),
('PVN233', 'Giấm táo OTTOGI 2L (can)', 78000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('bott', 'Bột ớt HaeNimCho Cánh to 1Kg (bịch)', 120000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('bot', 'Bột ớt HaeNimCho Mịn 1Kg (bịch)', 120000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN232', 'Bánh gạo thỏi Greenfood 1Kg (bịch)', 60000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('gvi', 'Gà viên Popcorn CP 1kg (bịch)', 120000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gà rán/Gà chiên']::TEXT[], NULL),
('PVN230', 'Mì ý REGINA 400g (bịch)', 25000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('PVN228', 'Xốt gà rán kiểu Hàn OTOKI 2Kg (túi)', 125000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gia vị & Xốt', 'Gà rán/Gà chiên']::TEXT[], NULL),
('PVN227', 'Rong biển cuộn cơm SUSHINORI 100 lá (bịch)', 255000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('PVN226', 'Cá thác lát rút xương (con)', 30000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN225', 'Há cảo tôm 25 viên (bịch)', 70000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN224', 'Bột ớt Đài Loan', 32000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN221', 'Cá thác lác rút xương (kg)', 100000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN220', 'Cá trích ép trứng NISSI 160g (thanh)', 95000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN219', 'Tương đậu truyền thống 500g (hộp)', 60000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN218', 'Wasabi NISSI 1kg (bịch)', 250000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('PVN216', 'Há cảo mini 50 viên (vỉ)', 50000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN215', 'Gừng hồng ROHI 1.5kg (bịch)', 140000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL);