INSERT INTO products (sku, name, price, description, tags, image_url) VALUES 
('xxpm', 'Xúc xích Phúc Minh 500g (gói)', 35000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN121', 'Dầu mè Chack Han Nongwoo 3L (can)', 500000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('cgrxnd', 'Chân gà rút xương Net 1kg (bịch)', 105000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('Gvcp', 'Gà Vòng CP 1Kg (bịch)', 110000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('Pmk', 'Phô mai khối Vilvi 2.5kg (khối)', 400000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('PVN118', 'Sốt ướp heo cay Bulgogi 10kg (can)', 720000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('rbcc', 'Rong biển KWOOK 100 lá (gói)', 290000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('Cj', 'Tương trộn Samjang CJ 14kg (thùng)', 750000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('Dasida', 'Hạt nêm bò DASIDA 1kg (bịch)', 190000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN117', 'Cá viên AQ CP 1kg (bịch)', 80000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('Cvht', 'Cá viên hành tiêu Tân Khánh 500g (gói)', 28000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('PVN116', 'Xốt gà CHUNGWOO vị cay 2.1kg (chai)', 160000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN115', 'Rong biển nấu canh 100g (gói)', 80000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('PVN114', 'Gà Nugget vòng 300g (gói)', 45000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('PVN111', 'Chả giò tôm thịt LC (gói)', 60000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Xúc xích & Chả cá', 'Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('PVN110', 'Tương ớt SINGSONG 14kg (thùng)', 700000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('PVN109', 'Rong biển nấu canh 200g (gói)', 135000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('Thv', 'Tôm hùm viên 500g (gói)', 50000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('Bbln', 'Bánh bao không nhân (gói)', 22000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Dimsum & Bánh ăn vặt']::TEXT[], NULL),
('cclv', 'Chả cá Hàn Quốc - Vàng (gói)', 35000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN106', 'Nước tương JIN MONGGO 13L (can)', 500000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('LKV', 'Rong biển vụn trộn cơm (gói)', 165000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('MNW', 'Miến Dangmyun NongWoo 1kg (bịch)', 75000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Mì Hàn Quốc']::TEXT[], NULL),
('MDNW', 'Miến dẹt NongWoo (kg)', 90000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Mì Hàn Quốc']::TEXT[], NULL),
('GTCO', 'Giấm táo Chef One 15L (can)', 400000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('cs', 'Chả cá sợi 500g (gói)', 35000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN103', 'Ghẹ Farci (vỉ)', 60000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('xxhl', 'Xúc xích hồ lô 500g (gói)', 45000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN101', 'Surimi mặt cười (gói)', 45000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('cv', 'Chả cua viên 500g (gói)', 55000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Xúc xích & Chả cá', 'Viên thả lẩu']::TEXT[], NULL),
('tchq', 'Thanh cua Hàn Quốc 1kg (bịch)', 125000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('nonvang', 'Trứng gà non vàng 1kg (bịch)', 140000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('cclx', 'Chả cá Hàn Quốc - Xanh (gói)', 40000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('PVN94', 'Củ cải vàng (hộp 2,6kg)', 160000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('dshn', 'Dồi sụn Hà Nội 500g (bịch)', 35000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('cmxo', 'Chả mực xoắn ống 500g (gói)', 45000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('CGRX', 'Chân gà rút xương NET5 (kg)', 105000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('SGCP', 'Sụn gà CP (kg)', 190000, 'Thực phẩm tươi ngon, được chọn lọc kỹ càng, sơ chế sạch sẽ và bảo quản nghiêm ngặt.', ARRAY['Khác']::TEXT[], NULL),
('BVPM', 'Bò viên Phúc Minh 500g (gói)', 32000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('ONPM', 'Ốc nhồi Phúc Minh 500g (gói)', 35000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Khác']::TEXT[], NULL),
('CTCPM', 'Chả trứng cút Tân Khánh 500g (gói)', 35000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('TVPM', 'Tôm viên Phúc Minh 500g (gói)', 30000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('CCDNH', 'Chả cá dài Ngọc Hải 500g (gói)', 40000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('CJ500', 'Tương ớt Gochujang CJ 500g (hộp)', 75000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('BVGTD', 'Bò viên gân Thành Đạt 500g (gói)', 40000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('KOTOKKY', 'Bánh gạo cuộn xúc xích (kg)', 120000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Bánh gạo/Tokbokki', 'Xúc xích & Chả cá']::TEXT[], NULL),
('bgpm', 'Bánh gạo phô mai Sannadle 500g (gói)', 60000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Bánh gạo/Tokbokki', 'Phô mai']::TEXT[], NULL),
('CVPM', 'Cá viên Phúc Minh 500g (gói)', 28000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('Hotdog', 'Hotdog Hàn Quốc 500g (hộp)', 45000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('CCC', 'Cá viên sốt Mayonaise cam 500g (vỉ)', 45000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Gia vị & Xốt', 'Viên thả lẩu']::TEXT[], NULL);