INSERT INTO products (sku, name, price, description, tags, image_url) VALUES 
('CHEPO', 'Bột phô mai O!Sajang 250g (gói)', 50000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Gia vị & Xốt', 'Phô mai']::TEXT[], NULL),
('udon200', 'Mì Udon Bongojang 200g (gói)', 16000, 'Mì ăn liền cao cấp, sợi mì dai giòn kết hợp nước súp hoặc nước xốt đậm đà chuẩn vị, vô cùng tiện lợi.', ARRAY['Mì Hàn Quốc', 'Gia vị & Xốt']::TEXT[], NULL),
('RBR100', 'Rong biển Roasted Laver 100 lá (gói)', 225000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Rong biển']::TEXT[], NULL),
('SUP', 'Sup chả cá Hàn Quốc 500g (gói)', 50000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('SK1', 'Tương ớt Hàn Quốc - Loại 1 (gói)', 60000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('SK200', 'Tương ớt Hàn Quốc - Loại 1 (gói) - 200g', 27000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('M', 'Bánh gạo Topokki', 65000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('M500', 'Bánh gạo truyền thống Sannadle đỏ 500g (bịch)', 65000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('XXBD', 'Xúc xích Tokyo 500g (gói)', 40000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('CCL', 'Chả cá Hàn Quốc (kg)', 50000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('CCQ', 'Chả cá Sajang dạng que 500g (gói)', 50000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('SDLC', 'Sò điệp LiChuan 500g (gói)', 70000, 'Sản phẩm thực phẩm chất lượng cao, quy trình đóng gói an toàn, đảm bảo tiêu chuẩn vệ sinh thực phẩm.', ARRAY['Khác']::TEXT[], NULL),
('Pms', 'Phô mai sợi Mozzarella 1kg (bịch)', 190000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('dhpm', 'Đậu hủ phô mai Phú Mark 450g (gói)', 50000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('CC', 'Chả cá cốm xanh (vỉ)', 45000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('KTM', 'Khoai tây cọng 7mm 1kg (bịch)', 55000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('Dhpmeb', 'Đậu hủ phô mai EB 500g (gói)', 85000, 'Sản phẩm phô mai cao cấp béo ngậy, hương vị thơm ngon tự nhiên, giàu canxi và dưỡng chất.', ARRAY['Phô mai']::TEXT[], NULL),
('VLC', 'Viên thả lẩu (kg)', 50000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('VLV', 'Viên thả lẩu LC 500g - Vàng (gói)', 50000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('CUK', 'Bánh gạo lát Sannadle 1kg (bịch)', 67000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('M4', 'Bánh gạo thỏi xiên (kg)', 65000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('NR', 'Bánh gạo Nori 1kg (bịch)', 60000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('HST', 'Bánh gạo hoa sao tim 500g (gói)', 37000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Bánh gạo/Tokbokki']::TEXT[], NULL),
('Tdo', 'Tinh dầu ớt 550g (chai)', 140000, 'Gia vị và nước xốt chuyên dụng, chuẩn vị, giúp tăng hương vị đậm đà và màu sắc hấp dẫn cho món ăn.', ARRAY['Gia vị & Xốt']::TEXT[], NULL),
('XXWN', 'Xúc xích Winner CP (kg)', 50000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('KC5', 'Kim chi', 80000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('KC1', 'Kim chi - 1Kg', 75000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('KC500', 'Kim chi - 500g', 40000, 'Món ăn chế biến sẵn thơm ngon, tiện lợi, mang hương vị truyền thống độc đáo, dễ dàng thưởng thức tại nhà.', ARRAY['Khác']::TEXT[], NULL),
('XX', 'Xúc xích ZingZing CP 500g (bịch)', 45000, 'Xúc xích thơm ngon, thịt chắc và đậm vị, thích hợp cho các món ăn nhanh, nướng hoặc thả lẩu.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL),
('CRC', 'Cá viên rau củ CP 500g (gói)', 40000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Viên thả lẩu']::TEXT[], NULL),
('TCLA', 'Thanh cua Liên Anh 500g (gói)', 70000, 'Topping thả lẩu và chiên rán cao cấp, kết cấu dai giòn sần sật, đậm đà hương vị tự nhiên.', ARRAY['Xúc xích & Chả cá']::TEXT[], NULL);